[build]
  command = "pip install -r requirements.txt && python3 update_sitemap_gnral.py"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

# Configuración para servir archivos estáticos
[[headers]]
  for = "/articulos/*"
  [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html" 