name: Indexar URLs en Google cada 4 horas

on:
  schedule:
    - cron: '0 */4 * * *'  # Cada 4 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente si lo deseas

jobs:
  indexar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 0. Instalar Node.js
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 1. Crear el archivo de credenciales a partir del secreto
      - name: Crear archivo de credenciales Google
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > ${{ github.workspace }}/indexing-service-account.json
          echo "Archivo de credenciales creado en: ${{ github.workspace }}/indexing-service-account.json"
          ls -la ${{ github.workspace }}/indexing-service-account.json

      # 2. Exportar la variable de entorno para que tu script la use
      - name: Exportar variable de entorno
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/indexing-service-account.json" >> $GITHUB_ENV
          echo "Variable de entorno configurada: $GOOGLE_APPLICATION_CREDENTIALS"

      # 3. Instalar dependencias necesarias
      - name: Instalar dependencias
        run: npm install googleapis

      # 4. Ejecutar tu script de indexación
      - name: Ejecutar indexador
        run: node google-indexing.js
