# name: Actualizar Lista de Artículos
#
# on:
#   push:
#     paths:
#       - 'articulos/**'
#     branches:
#       - main
#   workflow_dispatch: # Permite ejecutar manualmente
#   schedule:
#     - cron: '0 */2 * * *'
#
# jobs:
#   update-articles-json:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - name: Checkout código
#       uses: actions/checkout@v4
#       with:
#         fetch-depth: 0 # Necesario para obtener el historial completo
#     
#     - name: Configurar Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18'
#     
#     - name: Instalar dependencias
#       run: npm install
#     
#     - name: Actualizar lista de artículos
#       run: node update-json-local.js
#     
#     - name: Verificar cambios
#       id: check_changes
#       run: |
#         if git diff --quiet articulos-list.json; then
#           echo "changes=false" >> $GITHUB_OUTPUT
#         else
#           echo "changes=true" >> $GITHUB_OUTPUT
#         fi
#     
#     - name: Commit y push cambios
#       if: steps.check_changes.outputs.changes == 'true'
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git add articulos-list.json sistemapGNRAL.xml news-sitemap.xml
#         git commit -m "Actualizar lista de artículos y sitemap automáticamente"
#         git push 
#
#     - name: Notificar a Bing con IndexNow
#       run: node indexnow.js